# Generated by Django 3.0.7 on 2020-07-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webApp', '0002_auto_20200706_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=20)),
                ('bco_ag_d_sal', models.IntegerField()),
                ('cta_dep_sal', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('banco', models.CharField(max_length=25)),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('operacao', models.IntegerField()),
                ('numero_card', models.IntegerField()),
                ('confirmado', models.DateField()),
                ('matricula_cemig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Funcionario')),
            ],
            options={
                'verbose_name_plural': 'financeiro',
                'ordering': ('funcionario',),
            },
        ),
    ]
