# Generated by Django 3.0.7 on 2020-07-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=7)),
                ('bco_ag_d_sal', models.IntegerField()),
                ('cta_dep_sal', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('banco', models.CharField(max_length=25)),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('operacao', models.IntegerField()),
                ('numero_card', models.IntegerField()),
                ('confirmado', models.DateField()),
            ],
        ),
    ]
