# Generated by Django 3.0.7 on 2020-07-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
        ('Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ('funcionario',), 'verbose_name_plural': 'financeiro'},
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='matricula',
        ),
        migrations.AddField(
            model_name='financeiro',
            name='matricula_cemig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Funcionario'),
        ),
    ]
