# Generated by Django 3.0.7 on 2020-07-07 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=7)),
                ('pis', models.CharField(max_length=15)),
                ('dias_semana', models.IntegerField()),
                ('dias_pagar', models.IntegerField()),
                ('vale_transporte', models.BooleanField()),
                ('opcao', models.CharField(max_length=25)),
                ('tarifa_ida', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tarifa_volta', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_dia', models.IntegerField()),
                ('saldo_mes', models.DecimalField(decimal_places=2, max_digits=3)),
                ('recarregar', models.BooleanField()),
                ('doc_pendente', models.BooleanField()),
                ('folha_ponto', models.BooleanField()),
                ('ferias_inicio', models.DateField()),
                ('termino_ferias', models.DateField()),
                ('ASO_periodico', models.CharField(choices=[('', ''), ('S', 'Sim'), ('S', 'Não')], max_length=1)),
                ('plano_saude', models.CharField(choices=[('', ''), ('S', 'Sim'), ('S', 'Não')], max_length=1)),
                ('plano_odonto', models.CharField(choices=[('', ''), ('S', 'Sim'), ('S', 'Não')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula_iki', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=10)),
                ('dt_nascimento', models.DateField()),
                ('nome_pai', models.CharField(max_length=30)),
                ('nome_mae', models.CharField(max_length=30)),
                ('pis', models.IntegerField()),
                ('equipe', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('', ''), ('ON', 'Ativo'), ('AW', 'Afastado'), ('VAC', 'Férias'), ('OFF', 'Desligado')], max_length=3)),
                ('agencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Agencia')),
            ],
            options={
                'verbose_name_plural': 'funcionario',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25, null=True, unique=True)),
                ('resumo', djrichtextfield.models.RichTextField(max_length=20)),
                ('dt_publicacao', models.DateField(auto_now=True)),
                ('publicacao', djrichtextfield.models.RichTextField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Funcionario')),
                ('titulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Treinamento')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='regiao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Regiao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Us'),
        ),
    ]
