# Generated by Django 3.0.7 on 2020-06-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provas',
            new_name='Prova',
        ),
    ]
