# Generated by Django 3.0.7 on 2020-06-22 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='cargo',
            new_name='funcao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Cargo'),
        ),
    ]
