# Generated by Django 3.0.7 on 2020-07-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='dt_admissao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='matricula_cemig',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_mae',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_pai',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pis',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula_iki',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='agencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Agencia'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='regiao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Regiao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Us'),
        ),
    ]
