# Generated by Django 3.0.7 on 2020-06-25 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.US'),
        ),
        migrations.AlterField(
            model_name='provas',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.Funcionario'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='autor',
            field=models.CharField(max_length=20),
        ),
    ]
