# Generated by Django 3.0.7 on 2020-06-25 01:52

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20200624_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='publicacao',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
